Feature/BDN-719 Integrate Yandex cpm (#223)
* Integrated Yandex Ads: banner+interstitial only

* Integrated Yandex Ads: banner+interstitial only

* YandexAds. Removed from DefaultAdapters

* YandexAds. Removed from settings.gradle.kts

* develop: updated CHANGELOG.md;

* develop: small improvements;

* BDN-719: updated yandex adapter to 7.3.0; implemented new interfaces;

* BDN-719: updated yandex adapter to 7.3.0; implemented new interfaces;

* BDN-719: updated yandex adapter to 7.3.0; implemented new interfaces;

---------

Co-authored-by: Aleksei Cherniaev <klukwist@gmail.com>

diff --git a/.github/workflows/pull_request.yaml b/.github/workflows/pull_request.yaml
--- a/.github/workflows/pull_request.yaml
+++ b/.github/workflows/pull_request.yaml
@@ -1,6 +1,6 @@
 name: Android CI
 
-on: [push,workflow_dispatch]
+on: [ push,workflow_dispatch ]
 
 jobs:
   lint_check:
@@ -16,9 +16,27 @@ jobs:
         with:
           java-version: 11
 
-      # Execute unit tests
+      # Execute KtLint check
       - name: KtLint check
         run: ./gradlew ktLintCheck
+
+  changelog_check:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v1
+        with:
+          fetch-depth: 2
+
+      # Check if the changelog has been updated
+      - name: Check Changelog Changes
+        id: changelog-check
+        run: |
+          files_changed=$(git diff --name-only --diff-filter=ACMRT HEAD^ HEAD | xargs)
+          if echo "$files_changed" | tr ' ' '\n' | grep -q "CHANGELOG.md"; then
+            echo "Changelog has been updated."
+          else
+            echo "Error: Changelog has not been updated." && exit 1
+          fi
 
   run_tests:
     runs-on: ubuntu-latest
